In [2]:
import numpy as np
from sklearn import preprocessing

In [3]:
data = np.array([[3, -1.5,  2, -5.4], [0,  4,  -0.3, 2.1], [1,  3.3, -1.9, -4.3]])

In [4]:
data

array([[ 3. , -1.5,  2. , -5.4],
       [ 0. ,  4. , -0.3,  2.1],
       [ 1. ,  3.3, -1.9, -4.3]])

In [5]:
data_standarized = preprocessing.scale(data)

In [6]:
data_standarized

array([[ 1.33630621, -1.40451644,  1.29110641, -0.86687558],
       [-1.06904497,  0.84543708, -0.14577008,  1.40111286],
       [-0.26726124,  0.55907936, -1.14533633, -0.53423728]])

In [7]:
print "\nMean = ", data_standarized.mean(axis=0)


Mean =  [  5.55111512e-17  -1.11022302e-16  -7.40148683e-17  -7.40148683e-17]


In [8]:
print "Std deviation =", data_standarized.std(axis=0)

Std deviation = [ 1.  1.  1.  1.]


In [9]:
data_normalized = preprocessing.normalize(data, norm='l1')
print "\nL1 normalized data =", data_normalized


L1 normalized data = [[ 0.25210084 -0.12605042  0.16806723 -0.45378151]
 [ 0.          0.625      -0.046875    0.328125  ]
 [ 0.0952381   0.31428571 -0.18095238 -0.40952381]]
