In [1]:
import numpy

In [2]:
vector = numpy.array([5, 10, 15, 20])
equal_to_ten = (vector == 10)

print(vector[equal_to_ten])

[10]


In [5]:
matrix = numpy.array([
                [5, 10, 15], 
                [20, 25, 30],
                [35, 40, 45]
             ])
second_column_25 = (matrix[:,1] == 25)

In [6]:
second_column_25

array([False,  True, False], dtype=bool)

In [7]:
print(matrix[second_column_25, :])

[[20 25 30]]


In [8]:
matrix[:,0]

array([ 5, 20, 35])

In [9]:
matrix[:,0]==5

array([ True, False, False], dtype=bool)

In [10]:
matrix[matrix[:,0]==5, :]

array([[ 5, 10, 15]])

In [11]:
matrix[0]

array([ 5, 10, 15])

In [12]:
vector = numpy.array([5, 10, 15, 20])
equal_to_ten_or_five = (vector == 10) | (vector == 5)

In [13]:
equal_to_ten_or_five

array([ True,  True, False, False], dtype=bool)

In [14]:
vector[equal_to_ten_or_five]

array([ 5, 10])

In [16]:
vector[equal_to_ten_or_five]=50

In [18]:
vector

array([50, 50, 15, 20])

In [21]:
vector[0]

50

In [22]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
matrix[0,0]

5

In [24]:
matrix[0][0]

5

In [29]:
matrix[[True, True, False],:]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [32]:
vector2 = numpy.array([5, 10, 15, 20])
equal_to_ten_or_twenty = (vector2 == 10) | (vector2 == 20)

In [33]:
equal_to_ten_or_twenty

array([False,  True, False,  True], dtype=bool)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
matrix[:,0]

array([ 5, 20, 35])

In [36]:
matrix[:,0][matrix[:,0]==35]

array([35])

In [38]:
matrix[:,0][matrix[:,0]==35] =50

In [39]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [50, 40, 45]])

In [40]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [50, 40, 45]])

In [41]:
matrix[:,0]==50

array([False, False,  True], dtype=bool)

In [42]:
matrix2 = numpy.array([
                [5, 10, 15], 
                [20, 25, 30],
                [35, 40, 45]
             ])

In [45]:
matrix2.sum(axis=1)

array([60, 75, 90])

In [46]:
matrix2.sum(axis=0)

array([60, 75, 90])